config/routes.rb
Rails.application.routes.draw do

  get 'faq' => 'faqs#index'

  get 'reportes/ingresos'

  get 'reportes/gauchadas'

  get 'search/:frase' => 'home#search'
  get 'search/:frase/:ciudad' => 'home#search'
  get 'postulacions/cambiar_estado_aceptado' => 'postulacions#cambiar_estado_aceptado'
  get 'postulacions/cambiar_estado_rechazado' => 'postulacions#cambiar_estado_rechazado'
  get 'gauchadas/concretada' => 'gauchadas#cambiar_estado_concretada'
  get 'gauchadas/no_concretada' => 'gauchadas#cambiar_estado_no_concretada'

  devise_for :usuarios, controllers: {
    registrations: 'registrations'
  }
  resources :usuarios, only: [:show]
  resources :answers
  resources :questions
  resources :gauchadas do
      member do
        get :ver_listado
        get :terminar
      end
    end
  resources :logros
  resources :compras
  resources :postulacions

  root 'gauchadas#index'

end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :gauchada
	belongs_to :usuario
	has_one :answer, dependent: :destroy
	validates :contenido, presence: true
	validates :usuario, presence: true
	validates :gauchada, presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  load_and_authorize_resource param_method: :question_params
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.usuario = current_usuario

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question.gauchada, notice: 'Pregunta enviada.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question.gauchada, notice: 'Pregunta enviada.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:contenido, :gauchada_id, :usuario_id)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<% if @question != nil %>
<%= form_for(@question) do |f| %>

  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= f.hidden_field :gauchada_id, value: @gauchada.id %>
 <div class="reply-form">
    <h1 class="section-heading">Hace una pregunta </h1>
    <p class="text-xs-center">
      <%= @question.usuario.nombre %> <%= @question.usuario.apellido %>
    </p>

    <!--Third row-->
    <div class="row">
        <!--Image column-->
        <div class="col-sm-2 col-xs-12">
            <%= image_tag @question.usuario.imagen %>
        </div>
        <!--/.Image column-->

        <!--Content column-->
        <div class="col-sm-10 col-xs-12">
            <div class="md-form">
                <%= f.text_area :contenido , required: true, class: 'md-textarea' %>
                <%= f.label :contenido, 'Tu pregunta' %>
            </div>

        </div>

        <div class="text-xs-center">
            <button type="submit" class="btn btn-primary">Preguntar</button>
        </div>
        <!--/.Content column-->

    </div>
    <!--/.Third row-->
</div>
<% end %>

app/views/questions/_question.html.erb
<!--First row-->
<div class="row">
    <!--Image column-->
    <div class="col-sm-2 col-xs-12">
        <%= image_tag question.usuario.imagen %>
    </div>
    <!--/.Image column-->

    <% if can? :destroy, question %>
      <%= link_to question, class:'btn-floating btn red pull-right', data: { confirm: "¿Desea eliminar la Pregunta?" },
      method: :delete do%>
        <i class="fa fa-trash"></i>
      <% end %>
    <% end %>

    <!--Content column-->
    <div class="col-sm-10 col-xs-12">
        <a>
            <h5 class="user-name">
                <%= question.usuario.nombre %>
                <%= question.usuario.apellido %>
            </h5>
        </a>
        <div class="card-data text-xs-left text-xs-small">
            <ul>
                <li class="comment-date">
                    <i class="fa fa-clock-o"></i> Hace <%= time_ago_in_words question.updated_at %>
                </li>
            </ul>
        </div>

        <p class="comment-text">
            <%= question.contenido %>
            <% if question.answer!=nil %>
                <%= render question.answer %>
            <% elsif %>
                <% if usuario_signed_in? && @gauchada.usuario == current_usuario %>
                    <%= form_for @answer=Answer.new do |f| %>
                            <%= f.hidden_field :question_id, value: question.id %>
                      <div class="field">
                        <%= f.label :contenido, 'Tu respuesta' %><br>
                        <%= f.text_field :contenido, required: true %>
                      </div>
                      <div class="actions text-xs-center pt-1">
                        <button type="submit" class="btn btn-primary">Responder</button>
                      </div>
                <% end %>
            <% end %>
            <% end %>


        </p>
    </div>
    <!--/.Content column-->

</div>
<!--/.First row-->

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Questions</h1>

<table>
  <thead>
    <tr>
      <th>Contenido</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.contenido %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Contenido:</strong>
  <%= @question.contenido %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>