config/routes.rb
Rails.application.routes.draw do

  get 'faq' => 'faqs#index'

  get 'reportes/ingresos'

  get 'reportes/gauchadas'

  get 'search/:frase' => 'home#search'
  get 'search/:frase/:ciudad' => 'home#search'
  get 'postulacions/cambiar_estado_aceptado' => 'postulacions#cambiar_estado_aceptado'
  get 'postulacions/cambiar_estado_rechazado' => 'postulacions#cambiar_estado_rechazado'
  get 'gauchadas/concretada' => 'gauchadas#cambiar_estado_concretada'
  get 'gauchadas/no_concretada' => 'gauchadas#cambiar_estado_no_concretada'

  devise_for :usuarios, controllers: {
    registrations: 'registrations'
  }
  resources :usuarios, only: [:show]
  resources :answers
  resources :questions
  resources :gauchadas do
      member do
        get :ver_listado
        get :terminar
      end
    end
  resources :logros
  resources :compras
  resources :postulacions

  root 'gauchadas#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= Usuario.new # guest user (not logged in)
    if user.rol == "Admin"
      alias_action :create, :read, :update, :destroy, :to => :admPuede1
      alias_action :create, :read, :destroy, :to  => :admPuede2
      alias_action :ver_listado, :update, :terminar, :cambiar_estado_concretada,
      :cambiar_estado_no_concretada, :to => :admPuede3
      alias_action :create, :update, :destroy, :cambiar_estado_aceptado, :cambiar_estado_rechazado, :to =>:post

      can :admPuede1, Logro
      can :admPuede2, Answer
      can :admPuede2,  Question
      can :admPuede2, Gauchada

      can :admPuede3, Gauchada do |gauchada|
        gauchada.usuario == user
      end

      can :update, Answer do |gauchada|
        gauchada.usuario == user
      end

      can :update, Question do |gauchada|
        gauchada.usuario == user
      end

      can :post, Postulacion

      can :read, :all

    else if user.rol == "UsReg"
      alias_action :read, :update, :destroy, :ver_listado, :terminar, :cambiar_estado_concretada,
      :cambiar_estado_no_concretada, :to => :urPuede
      alias_action :create, :update, :destroy, :cambiar_estado_aceptado, :cambiar_estado_rechazado, :to =>:post

      can :create, Answer
      can :urPuede, Answer do |answer|
        answer.usuario == user
      end
      can :create, Question
      can :urPuede, Question do |question|
        question.usuario == user
      end
      can :create, Gauchada

      can :urPuede, Gauchada do |gauchada|
        gauchada.usuario == user
      end

      can :post, Postulacion

      can :read, :all
    else
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question
	validates :contenido, presence: true
end

app/models/compra.rb
class Compra < ActiveRecord::Base
	@tajerta

	validates :puntos_comprados, presence:true

	before_save :check_for_valido

	attr_accessor :tarjeta


	private 

	def check_for_valido
		if self.puntos_comprados <= 0 then
			self.errors[:base] << "Debe comprar al menos un punto"
			return false
		end
	end
end

app/models/gauchada.rb
class Gauchada < ActiveRecord::Base
	belongs_to :usuario
	has_many :questions, dependent: :destroy
	has_many :postulacions
	validates :titulo, :descripcion, :ciudad, presence: true
	#default_scope -> {order ("created_at DESC")}


	RXP = 10;

	def self.cantidad_paginas(options = {})
		aux = self.filter(options).size()
		if aux % RXP == 0
			return aux / RXP
		else
			return aux / RXP + 1
		end
	end

	def self.resultados(options = {})
		options = options || {}
		options.reverse_merge!(
				:pagina => 1
		)
		return self.filter(options).order("created_at DESC").limit(RXP).offset((options[:pagina].to_i-1)*RXP)
	end

	private

	def self.filter(options = {})
		 options[:ciudad] = options[:ciudad]=='*' ? nil : options[:ciudad]
		 options[:frase] = options[:frase].blank? ? nil : options[:frase]

		 if !options[:frase] && !options[:ciudad] then ## no hay frase ni cuidad
		   return Gauchada.all
		 elsif !options[:frase] && options[:ciudad] # no hay frase pero hay ciudad
		   return Gauchada.where("ciudad = ?",options[:ciudad])
		 elsif options[:frase] && !options[:ciudad] # hay frase pero no hay ciudad
		   return Gauchada.where("
		             (titulo  ILIKE ? OR
		             descripcion ILIKE  ? )",'%'+options[:frase].downcase+'%','%'+options[:frase].downcase+'%')
		 else # hay frase y hay ciudad
		   return Gauchada.where("
		       (titulo ILIKE ? OR
		       descripcion ILIKE ? ) AND
		       ciudad = ?",'%'+options[:frase].downcase+'%','%'+options[:frase].downcase+'%',options[:ciudad])
		 end
	end

end

app/models/logro.rb
class Logro < ActiveRecord::Base
	validates :titulo, :min,:max, presence:true, uniqueness: {case_sensitive: false}
	validates :min,:max, numericality: true

	before_destroy :check_for_unico
	
	before_save :check_for_rango_valido
	before_create :check_for_solapa_create
	before_update :check_for_solapa_update

	private

	def check_for_unico
	  unless Logro.all.size > 1
	  #unless puntaje != -2147483648
	    self.errors[:base] << "Debe haber al menos un logro"
	    return false
	  end
	end
	
	def check_for_rango_valido
	  if min > max
	    self.errors[:base] << "El máximo no puede ser menor que el mínimo"
	    return false
	  end
	end
	
	def check_for_solapa_create
	  res = Logro.where("(titulo<>?)				AND
	   			((min <= ? AND max >= ?) OR 
	   			 (min <= ? AND max >= ?) OR 
	   			 (min >= ? AND max <= ?))",titulo,min,min,max,max,min,max)
	  if res.size>0
	    self.errors[:base] << "Este puntaje solapa con: "+res.pluck(:titulo).join(", ")
	    return false
	  end
	end
	
	def check_for_solapa_update
	  res = Logro.where("(id<>?)				AND
	   			((min <= ? AND max >= ?) OR 
	   			 (min <= ? AND max >= ?) OR 
	   			 (min >= ? AND max <= ?))",id,min,min,max,max,min,max)
	  if res.size>0
	    self.errors[:base] << "Este puntaje solapa con: "+res.pluck(:titulo).join(", ")
	    return false
	  end
	end
end

app/models/postulacion.rb
class Postulacion < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :gauchada
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :gauchada
	belongs_to :usuario
	has_one :answer, dependent: :destroy
	validates :contenido, presence: true
	validates :usuario, presence: true
	validates :gauchada, presence: true
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :gauchadas, dependent: :destroy
  has_many :postulacions
  validates :puntos, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable




  def logro
  	return Logro.where("min <=?",self.puntos).order(:min => :desc).first
  end

  def imagen
    self.image_url || 'def-profile.png'
  end

end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  def index
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def img_exts
		allowed = ['.GIF','.PNG','.JPG','.BMP']
		allowed = allowed.concat allowed.map(&:downcase)
		allowed.join ','
	end

	def ciudades
		Gauchada.select(:ciudad).order(:ciudad).distinct.pluck(:ciudad)
	end
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/gauchadas_helper.rb
module GauchadasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logros_helper.rb
module LogrosHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/reportes_helper.rb
module ReportesHelper
end

app/helpers/usuario_helper.rb
module UsuarioHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/_buscador.html.erb
<div class="container">
	<!--Search form-->
	<%= form_tag({controller: "gauchadas", action: "index"}, method: "get")	 do %>
    	<div class="row">
    <!-- <form class="form-inline"> -->
    		<div class="col-xs-12 col-sm-6 align-bottom">
				<div class="md-form">
				    <i class="fa fa-search prefix"></i>
				    <% if params[:frase] && params[:frase]!='*' %>
					<input type="text" id="frase-buscar" name="frase" class="form-control" value="<%= params[:frase] %>">
					<% else %>
				    <input type="text" id="frase-buscar" name="frase" class="form-control">
					<% end %>
				    <label for="frase">Buscar</label>
				</div>
    		</div>
    		<div class="col-xs-11 offset-xs-1 offset-sm-0 col-sm-4 align-bottom">
            	<div class="md-form">
				    <select id="ciudad-buscar" name="ciudad" class="form-control browser-default custom-select">
	                    <option value="*" >Ciudad</option>
	                    <% ciudades.each do |c| %>
	                    <% if c==params[:ciudad] %>
	                    <option value="<%= c %>" selected="true"><%= c %></option>
	                    <% else %>
	                    <option value="<%= c %>"><%= c %></option>
	                    <% end %>
	                    <% end %>
	                </select>
            	</div>
    		</div>
    		<div class="col-xs-12 text-xs-center col-sm-2 align-bottom">
    			<button type="submit" class="btn btn-orange">Filtrar</button>
				<!-- <a id="boton-buscar" class="btn btn-orange">Filtrar</a> -->
    		</div>

    	</div>
    <% end %>
    <!-- </form> -->
</div>

app/views/layouts/_error_show.html.erb
<% if modelo.errors.any? %>
<blockquote class="blockquote bq-danger">
    <p class="bq-title">Hay <%= pluralize(modelo.errors.count, "error","errores") %></p>
    <p>
    	El <%= modelo.class.to_s.humanize %> no puede ser guardado:
    	<ul>
			<% modelo.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
    </p>
</blockquote>
<% end %>

app/views/layouts/_header.html.erb
<header>
	<%= render 'layouts/menu' %>
	<div class="row text-xs-center">
		<%= image_tag 'logo-gauchada.png' %>
	</div>
</header>

app/views/layouts/_menu.html.erb
<% if current_usuario && can?(:update, Logro) %>
<nav class="navbar navbar-dark deep-purple navbar-fixed-top scrolling-navbar">
<% else %>
<nav class="navbar navbar-dark orange navbar-fixed-top scrolling-navbar">
<% end %>
    <!-- Collapse button-->
    <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#collapseEx2">
        <i class="fa fa-bars"></i>
    </button>

    <div class="container">
        <div class="collapse navbar-toggleable-xs" id="collapseEx2">
             <a class="navbar-brand" href="/">UG</a>
            <ul class="nav navbar-nav" style="display:inline-block;">
                <li class="nav-item active">
                  <%= link_to root_path,class:'nav-link' do %>
                  Inicio<span class="sr-only">(current)</span>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to 'FAQs', faq_path,class:'nav-link' %>
                </li>
                <% if !current_usuario || !can?(:update, Logro) %>
                    <li class="nav-item">
                        <%= link_to 'Crear Gauchada', new_gauchada_path,class:'nav-link' %>
                    </li>
                <% end %>
                <% if current_usuario %>
                     <% if can? :update, Logro %>
                        <li class="nav-item">
                            <%= link_to logros_path,class:'nav-link' do %>
                                Logros
                            <% end %>
                        </li>
                        <li class="nav-item">
                            <%= link_to 'Ingresos', {:controller => :reportes, :action => :ingresos}, {class:'nav-link'} %>
                        </li>
                        <li class="nav-item">
                            <%= link_to 'Gauchadas', {:controller => :reportes, :action => :gauchadas}, {class:'nav-link'} %>
                        </li>
                        <% else %>
                        <li class="nav-item">
                            <%= link_to 'Comprar puntos',new_compra_path,class:'nav-link' %>
                        </li>
                        <% end %>
                    
                <% end %>
                
            </ul>
            <ul class="nav navbar-nav nav-flex-icons">

            <% if current_usuario %>
                <li class="nav-item">
                      <%= link_to 'Mi Perfil', current_usuario, class:'nav-link' %>
                </li>
                <li class="nav-item">
                      <%= link_to 'Salir', destroy_usuario_session_path, data: { confirm: "¿Cerrar sesión?" },class:'nav-link',method: :delete %>
                </li>
               
            <% else %>
                <li class="nav-item">
                    <%= link_to 'Entrar', new_usuario_session_path,class:'nav-link' %></li>
                <li class="nav-item">
                    <%= link_to 'Registrarse', new_usuario_registration_path,class:'nav-link' %>
                </li>
            <% end %>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div>
</nav>

app/views/layouts/_no_autorizado.html.erb
<p class="lead">
	Iniciá sesión para <%= mensaje %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>gauchada.com</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<!--   <link href="https://fonts.googleapis.com/css?family=Enriqueta:400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato:300,300i,400,400i" rel="stylesheet"> -->
</head>


<body>


<%= render 'layouts/header' %>

<div class="container py-1">
	<% if notice || alert %>
	<div class="row" id="notice">
		<div class="col-xs-10 offset-xs-1 col-sm-6 offset-sm-3">
			<button type="button" id="close-notice" class="close" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
			<% if notice %>
			  <blockquote class="blockquote bq-success">
			      <p class="bq-title">Bien!</p>
			      <p><%= notice %></p>
			  </blockquote>
			<% end %>
			<% if alert %>
				<blockquote class="blockquote bq-danger">
				    <p class="bq-title">Ups!</p>
				    <p><%= alert %></p>
				</blockquote>
			<% end %>
		</div>
	</div>
	<% end %>
</div>
<section>
<%= yield %>
</section>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>